### PR TITLE
Add NuGet package badge

### PR DESCRIPTION
**Pull request by mcqueary**
@ColinSullivan1

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
@mcqueary Great idea.  The link isn't working for me in the branch.  Does it for you?

**Comment by mcqueary** [comment]
@ColinSullivan1 That's odd. I can preview it from the PR diff here in GitHub. Try clicking this link?

https://github.com/nats-io/csnats/blob/36b861f4a6af8448e3631a4f10d0310f1541d0c5/README.md

**Comment by mcqueary** [comment]
cursor_and_csnats_readme_md_at_36b861f4a6af8448e3631a4f10d0310f1541d0c5_ _nats-io_csnats

**Comment by ColinSullivan1** [comment]
@mcqueary - I can see the badge, clicking on it goes to a 404 for me.

**Comment by mcqueary** [comment]
Good catch. There was no target URL. Try now :)

**Pull request merged**
