### PR TITLE
Only error logging logged to Console.Error

### LINKED ISSUE #535: Default event handlers log to stderr.
## Defect
NATS.Client default event handlers log to stderr when you disconnect from NATS server. It will log the disconnected and closed events to stderr even when you explicitly ask to be disconnected by calling the Dispose method.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `NATS.Client` and `nats-server`:
NATS.client version: 0.14.3
nats-server verstion: 2.2.1

#### OS/Container environment:
Windows 10 Enterprise
OS Build 19042.1415

#### Steps or code to reproduce the issue:
This console creates connection with default options and then disposes it. Log to stderr is decorated to be Red and prefixed with [Error].  

```c#
using System;
using System.IO;
using System.Text;
using NATS.Client;

namespace ConnectionEventsLog
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleErrorWriterDecorator.SetToConsole();
            Options options = ConnectionFactory.GetDefaultOptions();

            //options.DisconnectedEventHandler = (sender, eventArgs) => { };
            //options.ClosedEventHandler = (sender, eventArgs) => { };

            using (IConnection connection = new ConnectionFactory().CreateConnection(options))
            {
                Console.WriteLine($"Connection state is {connection.State}");
            }

            Console.WriteLine("Connection disposed");

            Console.ReadKey();
        }
    }

    public class ConsoleErrorWriterDecorator : TextWriter
    {
        private readonly TextWriter _originalConsoleStream;

        public ConsoleErrorWriterDecorator(TextWriter consoleTextWriter)
        {
            _originalConsoleStream = consoleTextWriter;
        }

        public override void WriteLine(string value)
        {
            ConsoleColor originalColor = Console.ForegroundColor;
            Console.ForegroundColor = ConsoleColor.Red;

            _originalConsoleStream.WriteLine($"[Error] {value}");

            Console.ForegroundColor = originalColor;
        }

        public override Encoding Encoding => Encoding.Default;

        public static void SetToConsole()
        {
            Console.SetError(new ConsoleErrorWriterDecorator(Console.Error));
        }
    }
}
```
Output:
Actual

#### Expected result:
Default event handlers log events to stdout and errors to stderr

#### Actual result:
Default event handlers log events to stderr and errors to stderr

#### Some hints:
Here are the places in NATS.cs
WriteEvent methods both call Console.Error.WriteLine(...)
https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/NATS.cs#L216
https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/NATS.cs#L221

### PR DESCRIPTION
**Pull request by LaurensVergote**
Probably fixes https://github.com/nats-io/nats.net/issues/535

### CODE REVIEW

**Comment by scottf** [comment]
Please see https://github.com/nats-io/nats.net/issues/535#issuecomment-1026111716

**Review by scottf — APPROVED** [review]
LGTM

**Comment by scottf** [comment]
@LaurensVergote I'm ready to merge this change but there are 2 issues. 
1. You must sign your commit. (see this: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)
2. There has been another change in this file to fix a bug., please rebase.

If you want to be the author/contributor please take care of those 2 things, otherwise I can just make a new pr with the same changes.

**Comment by LaurensVergote** [comment]
@scottf My environment isn't set up with GitHub at the moment. It be best if you make a new PR.

**Pull request merged**
