### PR TITLE
Add Rx Support

### PR DESCRIPTION
**Pull request by nataly87s**
related to #149

Added a new project with `ToObservable` extension methods. The project doesn't have a reference to rx.net, and it can be published as a separate nuget package.

### CODE REVIEW

**Review by ColinSullivan1 — COMMENTED** [review]
@nataly87s , Thanks!   Would you mind adding a simple example, a test, and some documentation?

**Comment by nataly87s** [comment]
@ColinSullivan1 done

**Comment by ColinSullivan1** [comment]
@nataly87s , this is great, much appreciated.  I'll setup .NET 45 to sanity check there before merging, then will do a follow-on PR for 4.5.  Good stuff!

**Comment by ColinSullivan1** [comment]
@watfordgnf, What are your thoughts here?

**Comment by watfordgnf** [comment]
If its a separate package, I don't see much risk in including it.

**Comment by danielwertheim** [comment]
@ColinSullivan1 I do believe #304 covers this one.

**Comment by ColinSullivan1** [comment]
Rx support has been added in #304.  Again, thank you for the submission.  Even though it wasn't merged, this PR did inspire support of Rx in the NATS client.

**Pull request closed without merging**
