### PR TITLE
don't force adding scheme prefix to string

### PR DESCRIPTION
**Pull request by harrisa1**
users should be expected to write reasonable code, this also matches the rest of the clients, i.e. see https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/Options.java line 584

### CODE REVIEW

**Comment by harrisa1** [comment]
for our use case we need to use the tcp scheme, but this forces us to use nats, our other languages don't have this problem

**Comment by kozlovic** [comment]
@harrisa1 Actually all other supported clients are moving to support simplified URLs. That is, if no scheme/port is specified, the default scheme and port are added.

**Comment by harrisa1** [comment]
that sounds great, but this client didn't do that, it forced the string to start with "nats://" even if you might have already supplied a scheme, and didn't touch the port at all, i can update this request with the changes to support defaults, but that is not what this code was doing, if like us you specified a scheme that wasn't "nats://" this prefixed a second scheme which obviously wouldn't work

**Comment by kozlovic** [comment]
@harrisa1 Understood that current code is wrong to prepend nats:// without checking if a scheme is already set. I think that it would be addressed with bringing the changes done for other clients, but I am sure that @ColinSullivan1 would not mind a PR ;-)

**Comment by harrisa1** [comment]
no problem, updated with support for simplified urls and defaults

**Review by ColinSullivan1 — APPROVED** [review]
LGTM, I'm running some automated tests, when they pass I'll merge.  Thanks!

**Pull request merged**
