### PR TITLE
Explicitly created threads now set IsBackground=true to avoid prevent…

### PR DESCRIPTION
**Pull request by SkinnySackboy**
…ing a process using this library from terminating.

### CODE REVIEW

**Review by watfordgnf — APPROVED** [review]
Approved pending CI.

**Comment by ColinSullivan1** [comment]
Looks like something is up with CI...

**Review by ColinSullivan1 — APPROVED** [review]
LGTM.  Thanks!

**Comment by watfordgnf** [comment]
Resolves #353

**Pull request merged**
