### PR TITLE
remove debug and api warning

### PR DESCRIPTION
**Pull request by scottf**
Removing extraneous debug information from ordered consumer implementation.

### CODE REVIEW

**Comment by scottf** [comment]
@jlumsden-mts fixed from your comments on PR #610

**Comment by scottf** [comment]
Emergency merge to remove extraneous debug

**Comment by jlumsden-mts** [comment]
Thanks for the prompt fix @scottf, much appreciated

**Comment by jlumsden-mts** [comment]
Sorry, @scottf, still one more warning left here for WatchAll instead of Watch:
https://github.com/nats-io/nats.net/blob/51f16fb37f73c4fcf01aae672719bae9ec461978/src/NATS.Client/KeyValue/IKeyValue.cs#L146

**Pull request merged**
