### PR TITLE
Refactor & migrate to VS 2017 Format

### PR DESCRIPTION
**Pull request by dominic-pockit**
This PR expands upon the changes made in PR#194 to migrate the old style csproj files in to the new format used by VS 2017.

It also tidies up the folder structure when dealing with .net core vs .net by unifying the different frameworks into multi-platform project files, which build libraries for all supported frameworks simultaneously. This means there's no longer a ".net" and ".netcore" solution file, just one that covers both. Similarly, the separate build scripts have been unified to build for both frameworks.

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
Thanks!  I'll take a look!

**Comment by ColinSullivan1** [comment]
I think this will be a great contribution, certainly needs to happen soon.

Unfortunately, I ran into an issue...  On a clean windows 10 image, and fresh vs 2017 community install, I get the following:
screen shot 2018-01-11 at 9 37 56 am

I'll look a bit further.  Since this is OSS, we'll want to support community editions of VS.

**Comment by ColinSullivan1** [comment]
Just a heads up, I'm running into issues using VS 2017 community.

**Comment by ColinSullivan1** [comment]
@nataly87s, thank you for starting this upgrade conversation and the initial PR, @dominic-pockit, thanks for combining the projects here.  Great PR here.

I've found the problem I was having; it was with missing `project.json` files.  Perhaps VS 2017 professional doesn't need them, but VS 2017 community sure seems to.  

@dominic-pockit, I tried pushing a PR to your repo, but didn't have permission.  See https://github.com/nats-io/csharp-nats/tree/pockit-master for the added files.  Could one of you give it a try (or @dominic-pockit, you can update this PR with the files), and if it works for you I'll merge the changes in.

Thanks, and much appreciated!

**Comment by ColinSullivan1** [comment]
@sixlettervariables , a favor - would you mind giving [this branch](https://github.com/nats-io/csharp-nats/tree/pockit-master ) a shot, so I know it's not only my environment where it works  ;)

**Comment by sixlettervariables** [comment]
They all build:
```
1>------ Rebuild All started: Project: NATS.Client (NATS.Client\NATS.Client), Configuration: Release Any CPU ------
1>NATS.Client -> D:\Users\<username>\Source\Repos\csnats\NATS.Client\bin\Release\net45\NATS.Client.dll
1>NATS.Client -> D:\Users\<username>\Source\Repos\csnats\NATS.Client\bin\Release\netstandard1.6\NATS.Client.dll
2>------ Rebuild All started: Project: NATSUnitTests, Configuration: Release Any CPU ------
3>------ Rebuild All started: Project: Benchmark, Configuration: Release Any CPU ------
4>------ Rebuild All started: Project: QueueGroup, Configuration: Release Any CPU ------
5>------ Rebuild All started: Project: Requestor, Configuration: Release Any CPU ------
6>------ Rebuild All started: Project: Subscribe, Configuration: Release Any CPU ------
7>------ Rebuild All started: Project: Publish, Configuration: Release Any CPU ------
8>------ Rebuild All started: Project: Replier, Configuration: Release Any CPU ------
4>QueueGroup -> D:\Users\<username>\Source\Repos\csnats\examples\QueueGroup\bin\Release\net45\QueueGroup.exe
5>Requestor -> D:\Users\<username>\Source\Repos\csnats\examples\Requestor\bin\Release\net45\Requestor.exe
8>Replier -> D:\Users\<username>\Source\Repos\csnats\examples\Replier\bin\Release\net45\Replier.exe
7>Publish -> D:\Users\<username>\Source\Repos\csnats\examples\Publish\bin\Release\net45\Publish.exe
3>Benchmark -> D:\Users\<username>\Source\Repos\csnats\examples\Benchmark\bin\Release\net45\Benchmark.exe
6>Subscribe -> D:\Users\<username>\Source\Repos\csnats\examples\Subscribe\bin\Release\net45\Subscribe.exe
4>QueueGroup -> D:\Users\<username>\Source\Repos\csnats\examples\QueueGroup\bin\Release\netstandard1.6\QueueGroup.dll
8>Replier -> D:\Users\<username>\Source\Repos\csnats\examples\Replier\bin\Release\netstandard1.6\Replier.dll
3>Benchmark -> D:\Users\<username>\Source\Repos\csnats\examples\Benchmark\bin\Release\netstandard1.6\Benchmark.dll
5>Requestor -> D:\Users\<username>\Source\Repos\csnats\examples\Requestor\bin\Release\netstandard1.6\Requestor.dll
7>Publish -> D:\Users\<username>\Source\Repos\csnats\examples\Publish\bin\Release\netstandard1.6\Publish.dll
6>Subscribe -> D:\Users\<username>\Source\Repos\csnats\examples\Subscribe\bin\Release\netstandard1.6\Subscribe.dll
2>NATSUnitTests -> D:\Users\<username>\Source\Repos\csnats\NATSUnitTests\bin\Release\net45\NATSUnitTests.dll
2>NATSUnitTests -> D:\Users\<username>\Source\Repos\csnats\NATSUnitTests\bin\Release\netcoreapp1.0\NATSUnitTests.dll
========== Rebuild All: 8 succeeded, 0 failed, 0 skipped ==========
```
But there is the warning triangle for (most) Dependencies on every project, e.g. NETStandard1.6, .NETFramework 4.5, .NETCoreApp 1.0.

**Comment by ColinSullivan1** [comment]
@sixlettervariables Many thanks!  So I'll double check this, merge, then look at the warnings.

**Comment by ColinSullivan1** [comment]
I'll revisit this after KubeCon/CloudNativeCon next week.  Apologies for the delay.

**Comment by ColinSullivan1** [comment]
Cleaning up old issues.  I ended up migrating to the VS2017 community format, which should be compatible with VS2017 Professional.  I didn't migrate the changes to fold everything under one project, but need to.  I do appreciate the work put in!

**Pull request closed without merging**
