### PR TITLE
Custom inbox prefix

### PR DESCRIPTION
**Pull request by danielwertheim**
Adds support for custom inbox prefix to solve #237

### CODE REVIEW

**Comment by danielwertheim** [comment]
After discussion I reverted from functional generators to simple string prefix.

Not sure if you think there should be validation when assigning the value? Are there any specific rules that should be enforced then?

Will complement with test.

**Comment by ColinSullivan1** [comment]
Good point on validation....  You can validate with `Subscription.IsValidSubject(string subject)`

**Comment by danielwertheim** [comment]
@ColinSullivan1 Validation added. Still lacks one or two integration tests.

**Comment by danielwertheim** [comment]
@ColinSullivan1 @watfordgnf  I changed the validation as I do believe it can not be exactly as subjects. Might be wrong. Also added integration test which also found an issue. I've nothing else planned for this PR.

**Review by ColinSullivan1 — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
